development:
  adapter: postgresql
  encoding: unicode
  database: cbt
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cbt
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cbt
  pool: 5
  username: postgres
  password:
